### ISSUE TITLE
[BUG] dart_code_metrics  resolving error for local packages

### ISSUE THREAD

**Issue by furaiev** [dart-code-checker/dart-code-metrics#289]
When a project uses a local package, the analyzer can not resolve `dart-code-metrics`.

**Steps to reproduce:**
1) `git clone https://github.com/furaiev/dart_metrics_bug_proof.git`
2) `flutter pub get`
3) go through troubleshooting as of p.p. 4 https://github.com/dart-code-checker/dart-code-metrics/blob/master/TROUBLESHOOTING.md

**Result:** Could not resolve "package:dart_code_metrics/dart_code_metrics.dart"
<details>
<summary>Log</summary>

```
Could not resolve "package:dart_code_metrics/dart_code_metrics.dart" in /Users/admin/developer/projects/dart_metrics_bug_proof/testing_api.
#0      PluginManager.recordPluginFailure (package:analysis_server/src/plugin/plugin_manager.dart:469:7)
#1      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:51:17)
#2      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1913:22)
#3      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:293:16)
#4      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:122:29)
#5      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:647:34)
#6      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1037:37)
#7      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1103:16)
#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1111:13)
#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:629:9)
#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:396:22)
#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:346:14)
#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:285:16)
#13     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:237:38)
#14     _rootRun (dart:async/zone.dart:1354:13)
#15     _CustomZone.run (dart:async/zone.dart:1258:19)
#16     _runZoned (dart:async/zone.dart:1788:10)
#17     runZonedGuarded (dart:async/zone.dart:1776:12)
#18     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:233:5)
#19     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163:14)
#20     ByteStreamServerChannel.listen. (package:analysis_server/src/channel/byte_stream_channel.dart:103:26)
#21     _rootRunUnary (dart:async/zone.dart:1362:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#33     _rootRunUnary (dart:async/zone.dart:1362:47)
#34     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#46     _rootRunUnary (dart:async/zone.dart:1362:47)
#47     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#52     _StreamController._add (dart:async/stream_controller.dart:607:7)
#53     _StreamController.add (dart:async/stream_controller.dart:554:5)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:2144:41)
#55     _rootRunUnary (dart:async/zone.dart:1370:13)
#56     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#61     _StreamController._add (dart:async/stream_controller.dart:607:7)
#62     _StreamController.add (dart:async/stream_controller.dart:554:5)
#63     new _RawSocket. (dart:io-patch/socket_patch.dart:1680:33)
#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1192:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>

**Comment by incendial** [comment]
@furaiev isn't it the same problem as discussed in #254?

**Comment by furaiev** [comment]
@incendial not exactly.
I believe the plugin should work correctly without adding the dependency to each package inside the project.
It's ok if the plugin won't analyse the content of the internal packages, but it shouldn't at least throws errors in the `Analyzer Server Diagnostics`.
What do you think?

**Comment by incendial** [comment]
@furaiev sorry, I completely forgot to answer.

> I believe the plugin should work correctly without adding the dependency to each package inside the project.

I agree, that it should not require to   add a dependency to each package, but if I remember correctly that is how the plugin discovery process works for now.

So, it's more like an `analyzer_plugin` integration problem.

**Comment by incendial** [comment]
My bad, I thought that the problem is with the plugin, but it's about cli... Sorry!

**Comment by dkrutskikh** [comment]
@furaiev can you check version from master branch?

**Comment by furaiev** [comment]
sure, I'll do

**Comment by furaiev** [comment]
@incendial I believe that the raised issue is about the plugin. CLI works w/o errors:
```
flutter pub run dart_code_metrics:metrics lib
lib/main.dart:
Warning Parameter is unused, consider renaming it to _, __, etc. : 10:16 : avoid-unused-parameters https://github.com/dart-code-checker/dart-code-metrics/blob/3.x.x/doc/rules/avoid-unused-parameters.md
Warning Prefer trailing comma. : 23:9 : prefer-trailing-comma https://github.com/dart-code-checker/dart-code-metrics/blob/3.x.x/doc/rules/prefer-trailing-comma.md
Warning Prefer trailing comma. : 25:7 : prefer-trailing-comma https://github.com/dart-code-checker/dart-code-metrics/blob/3.x.x/doc/rules/prefer-trailing-comma.md
```

@dkrutskikh I've checked master version, here is a log with my comments:

<details>
<summary>Log</summary>


```
Analysis plugins


----------------------> this is begin of the root project path <----------------------------

dart-code-metrics-f660e2fc015eae6d9f18199c0fd4753dc16808fd
bootstrap package path: /Users/admin/developer/flutter/.pub-cache/git/dart-code-metrics-f660e2fc015eae6d9f18199c0fd4753dc16808fd/tools/analyzer_plugin

execution path: /Users/admin/.dartServer/.plugin_manager/9285068dab5f1403770713f86ebb15dc/analyzer_plugin/bin/plugin.dart

packages file path: /Users/admin/.dartServer/.plugin_manager/9285068dab5f1403770713f86ebb15dc/analyzer_plugin/.packages

name: Dart Code Metrics

version: 1.0.0-alpha.0

Associated contexts:

/Users/admin/developer/projects/dart_metrics_bug_proof
Performance:

analysis.setContextRoots [1846]

analysis.setPriorityFiles [1862]

analysis.setSubscriptions [1860]

plugin.versionCheck [35]

----------------------> this is the end of the root project path <----------------------------

----------------------> this is begin of the local package project path <----------------------------

dart_code_metrics
bootstrap package path: dart_code_metrics/tools/analyzer_plugin

execution path: null

packages file path: null

not running

Could not resolve "package:dart_code_metrics/dart_code_metrics.dart" in /Users/admin/developer/projects/dart_metrics_bug_proof/testing_api.
#0      PluginManager.recordPluginFailure (package:analysis_server/src/plugin/plugin_manager.dart:471:7)
#1      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:54:17)
#2      AnalysisDriver.configure (package:analyzer/src/dart/analysis/driver.dart:500:33)
#3      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:113:12)
#4      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:65:36)
#5      ContextManagerImpl._createAnalysisContexts (package:analysis_server/src/context_manager.dart:414:19)
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:264:5)
#7      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:392:22)
#8      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:348:14)
#9      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:287:16)
#10     AnalysisServer.handleRequest. (package:analysis_server/src/analysis_server.dart:236:38)
#11     _rootRun (dart:async/zone.dart:1354:13)
#12     _CustomZone.run (dart:async/zone.dart:1258:19)
#13     _runZoned (dart:async/zone.dart:1789:10)
#14     runZonedGuarded (dart:async/zone.dart:1777:12)
#15     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:232:5)
#16     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:14)
#17     ByteStreamServerChannel.listen. (package:analysis_server/src/channel/byte_stream_channel.dart:105:26)
#18     _rootRunUnary (dart:async/zone.dart:1362:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#26     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:155:13)
#27     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:130:5)
#28     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#30     _rootRunUnary (dart:async/zone.dart:1362:47)
#31     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#35     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#36     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#37     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#38     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#39     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:317:20)
#40     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#41     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#42     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#43     _rootRunUnary (dart:async/zone.dart:1362:47)
#44     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#49     _StreamController._add (dart:async/stream_controller.dart:607:7)
#50     _StreamController.add (dart:async/stream_controller.dart:554:5)
#51     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#52     _rootRunUnary (dart:async/zone.dart:1370:13)
#53     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#58     _StreamController._add (dart:async/stream_controller.dart:607:7)
#59     _StreamController.add (dart:async/stream_controller.dart:554:5)
#60     new _RawSocket. (dart:io-patch/socket_patch.dart:1696:33)
#61     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1208:14)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

</details>
